openapi: 3.1.0
info:
  title: API for the Anonymous Post Board
  version: 1.0.0
  description: This is an API for the Anonymous Post Board
paths:
  /posts:
    get:
      description: Retrieve posts from the DynamoDB table
      parameters:
        - in: query
          name: before
          schema:
            type: string
          description: ID of the item to return the items before
        - in: query
          name: latest
          schema:
            type: boolean
          description: If true, returns the latest items
        - in: query
          name: id
          schema:
            type: string
          description: ID of the item to return
        - in: query
          name: count
          schema:
            type: integer
          description: Number of items to return
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    content:
                      type: string
                    timestamp:
                      type: integer
                    votes:
                      type: integer
                    ttl:
                      type: integer
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "513":
          description: Invalid ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    put:
      description: Create a new post in the DynamoDB table
      requestBody:
        description: Post object to be created
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                timestamp:
                  type: integer
                votes:
                  type: integer
                ttl:
                  type: integer
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  content:
                    type: string
                  timestamp:
                    type: integer
                  votes:
                    type: integer
                  ttl:
                    type: integer
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    patch:
      description: Update an existing post in the DynamoDB table
      parameters:
        - in: query
          name: id
          schema:
            type: string
          description: ID of the item to update
      requestBody:
        description: Post object to be updated
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                timestamp:
                  type: integer
                votes:
                  type: integer
                ttl:
                  type: integer
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  content:
                    type: string
                  timestamp:
                    type: integer
                  votes:
                    type: integer
                  ttl:
                    type: integer
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    delete:
      description: Delete an existing post from the DynamoDB table
      parameters:
        - in: query
          name: id
          schema:
            type: string
          description: ID of the item to delete
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  content:
                    type: string
                  timestamp:
                    type: integer
                  votes:
                    type: integer
                  ttl:
                    type: integer
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "513":
          description: Invalid ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /replies:
    get:
      description: Retrieve replies from the DynamoDB table
      parameters:
        - in: query
          name: before
          schema:
            type: string
          description: ID of the item to return the items before
        - in: query
          name: latest
          schema:
            type: boolean
          description: If true, returns the latest items
        - in: query
          name: id
          schema:
            type: string
          description: ID of the item to return
        - in: query
          name: count
          schema:
            type: integer
          description: Number of items to return
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    content:
                      type: string
                    timestamp:
                      type: integer
                    votes:
                      type: integer
                    ttl:
                      type: integer
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "513":
          description: Invalid ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    put:
      description: Create a new reply in the DynamoDB table
      requestBody:
        description: Reply object to be created
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                parent_id:
                  type: integer
                content:
                  type: string
                timestamp:
                  type: integer
                votes:
                  type: integer
                ttl:
                  type: integer
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  parent_id:
                    type: integer
                  content:
                    type: string
                  timestamp:
                    type: integer
                  votes:
                    type: integer
                  ttl:
                    type: integer
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    patch:
      description: Update an existing reply in the DynamoDB table
      parameters:
        - in: query
          name: id
          schema:
            type: string
          description: ID of the item to update
      requestBody:
        description: Reply object to be updated
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                parent_id:
                  type: integer
                content:
                  type: string
                timestamp:
                  type: integer
                votes:
                  type: integer
                ttl:
                  type: integer
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  parent_id:
                    type: integer
                  content:
                    type: string
                  timestamp:
                    type: integer
                  votes:
                    type: integer
                  ttl:
                    type: integer
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    delete:
      description: Delete an existing reply from the DynamoDB table
      parameters:
        - in: query
          name: id
          schema:
            type: string
          description: ID of the item to delete
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  parent_id:
                    type: integer
                  content:
                    type: string
                  timestamp:
                    type: integer
                  votes:
                    type: integer
                  ttl:
                    type: integer
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "513":
          description: Invalid ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
