name: Page Build Tests

on:
  push:
    branches:
      - "**" # matches every branch
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: test anonymous-post-board/
        run: |
          cd anonymous-post-board/
          npm ci
          npm run build --if-present
        env:
          CI: true
